--- 
baseURL: "http://pratu16x7.com/"
languageCode: en-us
title: "Prateeksha Singh"
menu: 
  main: 
    - 
      identifier: home
      name: About me
      url: /
      weight: 1
    - 
      identifier: stories
      name: Stories
      url: /stories/
      weight: 2
    -
      identifier: creations
      name: Creations
      url: /creations/
      weight: 3
    -
      identifier: work
      name: Work
      url: /work/ 
      weight: 4

params:
  description: Welcome to potentially the best source for stuff I might have done, if any.
  images:
  - images/timon_minimal.png
  title: Prateeksha's Webplace
  og_image: images/timon_minimal.png
taxonomies:
  series: series
